name: React CI/CD Pipeline

# Trigger the workflow on push or pull request to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          repository: 'https://github.com/velvettouch1004/web3-react-metamask'

      # Set up Node.js (specify your Node version if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the React app
      - name: Build React app
        run: |
          npm run build

      # Deploy the build (e.g., to GitHub Pages, Netlify, Vercel, or your server)
      - name: Deploy to GitHub Pages
        run: |
          npm install gh-pages --save-dev
          npm run deploy
